name: '0x7B2'
favicon: null
layout_spectrum: 0.6984716879669577
typography_spectrum: 0.5367434378713369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.671408188296482
  lightness: 0.5253209774382412
  saturation: 0.6020979343447834
  rhythmicContrast: 0.9454617593437433
purpose: []
